kind = "web"
previewPath = "/"
title = "KixxMe"
version = "1.0.0"
id = "artifacts/kixxme"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18434

[services.development]
run = "pnpm --filter @workspace/kixxme run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kixxme", "run", "build" ]
publicDir = "artifacts/kixxme/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18434"
BASE_PATH = "/"
