import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import photosRouter from "./photos.js";
import conversationsRouter from "./conversations.js";
import messagesRouter from "./messages.js";
import profilesRouter from "./profiles.js";
import stripeRouter from "./stripe.js";
import subscriptionRouter from "./subscription.js";
import supportRouter from "./support.js";
import notificationsRouter from "./notifications.js";
import liveRouter from "./live.js";
import accountRouter from "./account.js";
import likesRouter from "./likes.js";
import reportsRouter from "./reports.js";
import verificationRouter from "./verification.js";
import rewardsRouter from "./rewards.js";
import adminRouter from "./admin.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(photosRouter);
router.use(conversationsRouter);
router.use(messagesRouter);
router.use(profilesRouter);
router.use(stripeRouter);
router.use(subscriptionRouter);
router.use(supportRouter);
router.use(notificationsRouter);
router.use(liveRouter);
router.use(accountRouter);
router.use(likesRouter);
router.use(reportsRouter);
router.use(verificationRouter);
router.use(rewardsRouter);
router.use(adminRouter);

export default router;
